### PR TITLE
Remove developers from parent pom

### PR DESCRIPTION
**Pull request by JanWittler**
In accordance with the update of the code owners, I removed the developers from the parent pom

### CODE REVIEW

**Review by HeikoKlare — COMMENTED** [review]
Unfortunately, I think this is not allowed when deploying to Maven central (https://central.sonatype.org/publish/requirements/#developer-information) 🙁

**Comment by JanWittler** [comment]
Oh, thanks for pointing that out. Maybe we setup a generic Vitruvius mailing list and then add a "generic" developer in the pom?

**Comment by HeikoKlare** [comment]
Yes, that makes sense. We also need to have an account registered for deploying artifacts to Sonatype's repository, which might make sense to be the same than the one added as a generic developer to the pom (in particular when we move to plain Java with more deployments to Maven central). I am not sure which account we currently use there. Maybe it is my university account or the vitruv.tools@gmail.com one we use for some generic purposes. We have to check that anyway, because the used Sonatype account should be one you have access to.

**Comment by HeikoKlare** [comment]
Just for documentation after I have checked: We use the `kitsdq` Sonatype user for deployments.

**Pull request closed without merging**
